name: mac-api-env
channels:
  - apple
  - conda-forge
dependencies:
  - anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1685486400275/work/dist
  - appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1649077682618/work
  - argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
  - argon2-cffi-bindings @ file:///Users/runner/miniforge3/conda-bld/argon2-cffi-bindings_1666850755229/work
  - asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
  - attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
  - backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
  - backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
  - beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
  - bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
  - blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1681349778161/work
  - boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1687461086905/work
  - botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1687459105924/work
  - brotlipy @ file:///Users/runner/miniforge3/conda-bld/brotlipy_1666764778428/work
  - cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
  - absl-py==1.4.0
  - arrow==1.2.3
  - astunparse==1.6.3
  - bayesian-optimization==1.4.3
  - bs4==0.0.1
  - cachetools==5.3.1
  - canvasapi==3.2.0
  - certifi==2023.5.7
  - cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1671179432479/work
  - charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-\xE5\normalizer_1678108872112/work
  - click @ file:///home/conda/feedstock_root/build_artifacts/click_1666798198223/work
  - cloudpickle==2.2.1
  - colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
  - comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
  - contourpy @ file:///Users/runner/miniforge3/conda-bld/contourpy_1686734108934/work
  - cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography-split_1685659611910/work
  - cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
  - debugpy @ file:///Users/runner/miniforge3/conda-bld/debugpy_1680755636886/work
  - decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
  - defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
  - entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
  - exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1678703645500/work
  - executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
  - fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1684761244589/work/dist
  - Flask @ file:///home/conda/feedstock_root/build_artifacts/flask_1682966527207/work
  - flatbuffers==1.12
  - flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1684084314667/work/source/flit_core
  - fonttools @ file:///Users/runner/miniforge3/conda-bld/fonttools_1686578582263/work
  - gast==0.4.0
  - google-auth==2.20.0
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1653138941901/work
  - gym==0.26.2
  - gym-notices==0.0.8
  - h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1637964045648/work
  - idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
  - importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1687138353019/work
  - importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
  - ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1687387516473/work
  - ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1685727999785/work
  - ipython-genutils==0.2.0
  - ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1680023138361/work
  - itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1648147185463/work
  - jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
  - Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
  - jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1655568249366/work
  - joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
  - jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
  - jupyter @ file:///Users/runner/miniforge3/conda-bld/jupyter_1670249726915/work
  - jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1678118109161/work
  - jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
  - jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1681432441054/work
  - jupyter_core @ file:///Users/runner/miniforge3/conda-bld/jupyter_core_1686775920423/work
  - jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1685051725700/work
  - jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
  - jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
  - jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1684239754370/work
  - kaggle==1.5.13
  - keras==2.9.0
  - Keras-Preprocessing==1.1.2
  - kiwisolver @ file:///Users/runner/miniforge3/conda-bld/kiwisolver_1666805901953/work
  - libclang==16.0.0
  - lxml @ file:///Users/runner/miniforge3/conda-bld/lxml_1686749240927/work
  - Markdown==3.4.3
  - markdown2==2.4.9
  - MarkupSafe @ file:///Users/runner/miniforge3/conda-bld/markupsafe_1685769187476/work
  - matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-suite_1678135761655/work
  - matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
  - mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1686313613819/work/dist
  - munkres==1.1.4
  - nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1683202081046/work
  - nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1684790896106/work
  - nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1687202153002/work
  - nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1685541374434/work
  - nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
  - notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1680870634737/work
  - notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
  - numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1660672958449/work
  - oauthlib==3.2.2
  - opt-einsum==3.3.0
  - overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1666057828264/work
  - packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
  - pandas @ file:///Users/runner/miniforge3/conda-bld/pandas_1685343244584/work
  - pandas-datareader @ file:///home/conda/feedstock_root/build_artifacts/pandas-datareader_1626254169655/work
  - pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
  - parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
  - pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
  - pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
  - Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1684654233406/work
  - pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
  - platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1687097136512/work
  - pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
  - prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1684970902412/work
  - prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
  - protobuf==3.19.6
  - psutil @ file:///Users/runner/miniforge3/conda-bld/psutil_1681775391262/work
  - ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
  - pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
  - pyasn1==0.5.0
  - pyasn1-modules==0.3.0
  - pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
  - Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
  - pyobjc-core @ file:///Users/runner/miniforge3/conda-bld/pyobjc-core_1686129295146/work
  - pyobjc-framework-Cocoa @ file:///Users/runner/miniforge3/conda-bld/pyobjc-framework-cocoa_1686136045891/work
  - pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1685514481738/work
  - pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1687132014935/work
  - pyrsistent @ file:///Users/runner/miniforge3/conda-bld/pyrsistent_1672681609473/work
  - PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
  - python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
  - python-dotenv==1.0.0
  - python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
  - python-slugify==8.0.1
  - pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
  - PyYAML @ file:///Users/runner/miniforge3/conda-bld/pyyaml_1666772466414/work
  - pyzmq @ file:///Users/runner/miniforge3/conda-bld/pyzmq_1685519580454/work
  - requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
  - requests-oauthlib==1.3.1
  - rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
  - rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
  - rsa==4.9
  - s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1683241957497/work
  - scikit-learn @ file:///Users/runner/miniforge3/conda-bld/scikit-learn_1685023891036/work
  - scipy @ file:///Users/runner/miniforge3/conda-bld/scipy-split_1683900386585/work/base/dist/scipy-1.10.1-cp39-cp39-macosx_11_0_arm64.whl#sha256=b591fbc92acab6f17fdf631bc95166f008fc08def1e194f08d0f4332a121638c
  - Send2Trash @ file:///Users/runner/miniforge3/conda-bld/send2trash_1682601407921/work
  - six==1.15.0
  - sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
  - soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
  - stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
  - tensorboard==2.9.1
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorflow-estimator==2.9.0
  - tensorflow-macos==2.9.0
  - tensorflow-metal==0.5.0
  - termcolor==2.3.0
  - terminado @ file:///Users/runner/miniforge3/conda-bld/terminado_1670254106711/work
  - text-unidecode==1.3
  - threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
  - tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
  - tornado @ file:///Users/runner/miniforge3/conda-bld/tornado_1684150430519/work
  - tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
  - traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
  - typing-utils @ file:///home/conda/feedstock_root/build_artifacts/typing_utils_1622899189314/work
  - typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1685704949284/work
  - tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
  - unicodedata2 @ file:///Users/runner/miniforge3/conda-bld/unicodedata2_1667239959992/work
  - urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
  - wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
  - webencodings==0.5.1
  - websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1686999594811/work
  - Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1686273693854/work
  - widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1680021576815/work
  - wrapt==1.15.0
  - zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work